export type Category =
  | "编码转换"
  | "格式校验"
  | "文本处理"
  | "加密安全"
  | "Web 与网络"
  | "前端工具"
  | "后端工具"
  | "数据生成";
export type ToolCapability = "local" | "network" | "ai";
export type Tool = {
  id: string;
  name: string;
  desc: string;
  icon: string;
  color: string;
  category: Category;
  capability: ToolCapability;
  tag?: string;
};

type ToolDefinition = Omit<Tool, "capability">;

const connectedToolCapabilities: Record<string, Exclude<ToolCapability, "local">> = {};

export function getToolCapability(id: string): ToolCapability {
  return connectedToolCapabilities[id] ?? "local";
}

const toolDefinitions: ToolDefinition[] = [
  {
    id: "json",
    name: "JSON 格式化",
    desc: "格式化、压缩与语法校验",
    icon: "{ }",
    color: "cyan",
    category: "格式校验",
  },
  {
    id: "base64",
    name: "Base64 转换",
    desc: "文本的 Base64 编码解码",
    icon: "B64",
    color: "blue",
    category: "编码转换",
  },
  {
    id: "url",
    name: "URL 编解码",
    desc: "URL 和参数安全转换",
    icon: "%",
    color: "green",
    category: "编码转换",
  },
  {
    id: "unicode",
    name: "Unicode 转换",
    desc: "中文与 Unicode 互转",
    icon: "U+",
    color: "blue",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "timestamp",
    name: "时间戳转换",
    desc: "Unix 秒/毫秒与日期互转",
    icon: "◷",
    color: "orange",
    category: "编码转换",
    tag: "热门",
  },
  {
    id: "datecalc",
    name: "日期计算",
    desc: "计算两个日期时间之间的间隔",
    icon: "D±",
    color: "orange",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "timeunits",
    name: "时间单位转换",
    desc: "转换毫秒、秒、分钟、小时、天与周",
    icon: "t↔",
    color: "orange",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "iso8601",
    name: "ISO 8601 时间解析",
    desc: "解析并拆解标准日期时间与时区",
    icon: "ISO",
    color: "blue",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "semver",
    name: "SemVer 版本比较",
    desc: "比较主次修订号、预发布版本和构建元数据",
    icon: "v·",
    color: "purple",
    category: "后端工具",
    tag: "新",
  },
  {
    id: "dateconvert",
    name: "日期转换",
    desc: "批量转换时间戳、日期与日期时间",
    icon: "D↔",
    color: "blue",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "filesize",
    name: "文件大小转换",
    desc: "转换 B、KB、MB、GB 与 KiB、MiB、GiB",
    icon: "B↔",
    color: "cyan",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "radix",
    name: "进制转换",
    desc: "2、8、10、16 进制同时转换",
    icon: "01",
    color: "green",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "chinese",
    name: "简繁体转换",
    desc: "简体中文与繁体中文互转",
    icon: "简",
    color: "red",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "case",
    name: "大小写转换",
    desc: "英文字母大写与小写互转",
    icon: "Aa",
    color: "yellow",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "ascii",
    name: "ASCII 转换",
    desc: "字符与十进制编码数字互转",
    icon: "65",
    color: "cyan",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "escape",
    name: "字符串转义",
    desc: "添加或去除常用转义符",
    icon: "\\n",
    color: "purple",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "rmb",
    name: "人民币大写",
    desc: "人民币数字金额转中文大写",
    icon: "¥",
    color: "orange",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "pinyin",
    name: "汉字转拼音",
    desc: "汉字转拼音，支持声调格式和多音字候选",
    icon: "拼",
    color: "blue",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "hash",
    name: "Hash 计算",
    desc: "SHA-1 / SHA-256 / SHA-512",
    icon: "#",
    color: "purple",
    category: "加密安全",
  },
  {
    id: "md5-32-lower",
    name: "MD5加密32_小写",
    desc: "32 位小写 MD5 摘要",
    icon: "MD5",
    color: "cyan",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "md5-32-upper",
    name: "MD5加密32_大写",
    desc: "32 位大写 MD5 摘要",
    icon: "MD5",
    color: "blue",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "md5-16-lower",
    name: "MD5加密16_小写",
    desc: "16 位小写 MD5 摘要",
    icon: "M16",
    color: "green",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "md5-16-upper",
    name: "MD5加密16_大写",
    desc: "16 位大写 MD5 摘要",
    icon: "M16",
    color: "orange",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "sha1",
    name: "SHA1",
    desc: "SHA-1 消息摘要",
    icon: "S1",
    color: "purple",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "sha2-256",
    name: "SHA2_256",
    desc: "SHA-2 256 位消息摘要",
    icon: "256",
    color: "cyan",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "sha2-512",
    name: "SHA2_512",
    desc: "SHA-2 512 位消息摘要",
    icon: "512",
    color: "blue",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "sha3-512",
    name: "SHA3_512",
    desc: "SHA-3 512 位消息摘要",
    icon: "3·5",
    color: "green",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "sha3-384",
    name: "SHA3_384",
    desc: "SHA-3 384 位消息摘要",
    icon: "384",
    color: "orange",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "sha3-256",
    name: "SHA3_256",
    desc: "SHA-3 256 位消息摘要",
    icon: "3·2",
    color: "pink",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "sha3-224",
    name: "SHA3_224",
    desc: "SHA-3 224 位消息摘要",
    icon: "224",
    color: "red",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "ripemd-160",
    name: "RIPEMD_160",
    desc: "RIPEMD-160 消息摘要",
    icon: "R160",
    color: "yellow",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "aes-encrypt",
    name: "AES_Encrypt",
    desc: "使用口令进行 AES 加密",
    icon: "AES",
    color: "cyan",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "aes-decrypt",
    name: "AES_Decrypt",
    desc: "使用口令进行 AES 解密",
    icon: "AES",
    color: "blue",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "des-encrypt",
    name: "DES_Encrypt",
    desc: "使用口令进行 DES 加密",
    icon: "DES",
    color: "green",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "des-decrypt",
    name: "DES_Decrypt",
    desc: "使用口令进行 DES 解密",
    icon: "DES",
    color: "orange",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "tripledes-encrypt",
    name: "TripleDES_Encrypt",
    desc: "使用口令进行 Triple DES 加密",
    icon: "3DES",
    color: "pink",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "tripledes-decrypt",
    name: "TripleDES_Decrypt",
    desc: "使用口令进行 Triple DES 解密",
    icon: "3DES",
    color: "red",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "rabbit-encrypt",
    name: "Rabbit_Encrypt",
    desc: "使用口令进行 Rabbit 加密",
    icon: "RBT",
    color: "yellow",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "rabbit-decrypt",
    name: "Rabbit_Decrypt",
    desc: "使用口令进行 Rabbit 解密",
    icon: "RBT",
    color: "cyan",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "rc4-encrypt",
    name: "RC4_Encrypt",
    desc: "使用口令进行 RC4 加密",
    icon: "RC4",
    color: "blue",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "rc4-decrypt",
    name: "RC4_Decrypt",
    desc: "使用口令进行 RC4 解密",
    icon: "RC4",
    color: "green",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "crc32-64",
    name: "64位 CRC32",
    desc: "CRC32 的 64 位十六进制表示",
    icon: "CRC",
    color: "purple",
    category: "加密安全",
    tag: "新",
  },
  {
    id: "uuid",
    name: "UUID 生成器",
    desc: "批量生成 UUID v4",
    icon: "ID",
    color: "pink",
    category: "数据生成",
  },
  {
    id: "password",
    name: "密码生成器",
    desc: "安全随机密码批量生成",
    icon: "***",
    color: "red",
    category: "数据生成",
    tag: "新",
  },
  {
    id: "text",
    name: "文本工具",
    desc: "统计、清理与大小写转换",
    icon: "Aa",
    color: "yellow",
    category: "文本处理",
  },
  {
    id: "dedupe",
    name: "去重复行",
    desc: "删除重复内容，保留首次出现",
    icon: "≠",
    color: "cyan",
    category: "文本处理",
    tag: "新",
  },
  {
    id: "sortlines",
    name: "文本排序",
    desc: "按行自然升序或降序排列",
    icon: "↕",
    color: "green",
    category: "文本处理",
    tag: "新",
  },
  {
    id: "regex",
    name: "正则测试",
    desc: "实时检查匹配结果",
    icon: ".*",
    color: "orange",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "jwt",
    name: "JWT 解析",
    desc: "本地解析 Header 与 Payload",
    icon: "JWT",
    color: "red",
    category: "加密安全",
  },
  {
    id: "json2ts",
    name: "JSON 转 TypeScript",
    desc: "自动推断对象类型",
    icon: "TS",
    color: "blue",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "query",
    name: "URL 参数解析",
    desc: "解析 Query 参数为 JSON",
    icon: "?=",
    color: "cyan",
    category: "Web 与网络",
    tag: "新",
  },
  {
    id: "color",
    name: "HEX / RGB 转换",
    desc: "HEX 与 RGB 颜色值快速互转",
    icon: "◐",
    color: "pink",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "markdown",
    name: "Markdown 预览",
    desc: "快速转换为 HTML",
    icon: "MD",
    color: "purple",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "diff",
    name: "文本 Diff",
    desc: "逐行对比两段文本差异",
    icon: "±",
    color: "cyan",
    category: "文本处理",
    tag: "新",
  },
  {
    id: "naming",
    name: "命名格式转换",
    desc: "驼峰、下划线、短横线互转",
    icon: "aA",
    color: "yellow",
    category: "文本处理",
    tag: "新",
  },
  {
    id: "entities",
    name: "HTML 实体",
    desc: "HTML 实体编码与解码",
    icon: "&;",
    color: "orange",
    category: "编码转换",
    tag: "新",
  },
  {
    id: "cron",
    name: "Crontab 工具",
    desc: "支持 Linux、Spring 与 Quartz",
    icon: "⏱",
    color: "pink",
    category: "后端工具",
    tag: "新",
  },
  {
    id: "curl",
    name: "Curl 转 Fetch",
    desc: "将 Curl 请求转为 Fetch 代码",
    icon: "$",
    color: "green",
    category: "Web 与网络",
    tag: "新",
  },
  {
    id: "cidr",
    name: "CIDR 子网计算",
    desc: "计算 IPv4 网络与主机范围",
    icon: "IP",
    color: "blue",
    category: "Web 与网络",
    tag: "新",
  },
  {
    id: "units",
    name: "CSS 单位转换",
    desc: "px 与 rem 快速互转",
    icon: "px",
    color: "purple",
    category: "前端工具",
    tag: "新",
  },
  {
    id: "contrast",
    name: "颜色对比度",
    desc: "WCAG 对比度与等级检查",
    icon: "Aa",
    color: "cyan",
    category: "前端工具",
    tag: "新",
  },
  {
    id: "sql",
    name: "SQL 格式化",
    desc: "常用 SQL 关键字换行缩进",
    icon: "SQL",
    color: "orange",
    category: "后端工具",
    tag: "新",
  },
  {
    id: "yaml",
    name: "JSON 转 YAML",
    desc: "将 JSON 对象转为 YAML",
    icon: "YML",
    color: "red",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "yaml2json",
    name: "YAML 转 JSON",
    desc: "格式化并转换 YAML 数据",
    icon: "Y→J",
    color: "cyan",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "json2xml",
    name: "JSON 转 XML",
    desc: "JSON 数据转换为 XML",
    icon: "J→X",
    color: "blue",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "xml2json",
    name: "XML 转 JSON",
    desc: "XML 数据转换为 JSON",
    icon: "X→J",
    color: "green",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "json2csv",
    name: "JSON 转 CSV",
    desc: "对象数组转换为 CSV",
    icon: "J→C",
    color: "orange",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "csv2json",
    name: "CSV 转 JSON",
    desc: "带表头 CSV 转对象数组",
    icon: "C→J",
    color: "purple",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "jsonschema",
    name: "JSON Schema 校验",
    desc: "检查数据类型与必填字段",
    icon: "JS",
    color: "pink",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "yamlformat",
    name: "YAML 格式化",
    desc: "语法校验与标准化缩进",
    icon: "YF",
    color: "yellow",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "xmlformat",
    name: "XML 格式化",
    desc: "语法校验与层级缩进",
    icon: "XF",
    color: "red",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "webformat",
    name: "Web 代码格式化",
    desc: "HTML、CSS、JavaScript 格式化",
    icon: "</>",
    color: "cyan",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "csvpreview",
    name: "CSV 表格预览",
    desc: "解析 CSV 并生成表格视图",
    icon: "CSV",
    color: "blue",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "propertiesyaml",
    name: "Properties / YAML",
    desc: "Java Properties 与 YAML 互转",
    icon: "P↔Y",
    color: "green",
    category: "格式校验",
    tag: "新",
  },
  {
    id: "findreplace",
    name: "查找与批量替换",
    desc: "批量替换文本中的目标内容",
    icon: "F/R",
    color: "orange",
    category: "文本处理",
    tag: "新",
  },
  {
    id: "linefilter",
    name: "文本行过滤",
    desc: "按包含和排除条件筛选行",
    icon: "FIL",
    color: "purple",
    category: "文本处理",
    tag: "新",
  },
  {
    id: "shuffle",
    name: "文本随机打乱",
    desc: "安全随机打乱文本行",
    icon: "RND",
    color: "pink",
    category: "文本处理",
    tag: "新",
  },
  {
    id: "mdtable",
    name: "Markdown 表格生成器",
    desc: "CSV 数据生成 Markdown 表格",
    icon: "MDT",
    color: "yellow",
    category: "格式校验",
    tag: "新",
  },
];

export const tools: Tool[] = toolDefinitions.map((tool) => ({
  ...tool,
  capability: getToolCapability(tool.id),
}));

export const categories = [
  "全部工具",
  "常用收藏",
  "最近使用",
  "编码转换",
  "格式校验",
  "文本处理",
  "加密安全",
  "Web 与网络",
  "前端工具",
  "后端工具",
  "数据生成",
];
