import { p0Samples } from "./p0-tools";

export const toolSamples: Record<string, string> = {
  json: '{"project":"DevKit","ready":true,"tools":["JSON","Base64","UUID"]}',
  base64: "开发者工具箱",
  url: "https://example.com/search?q=开发者工具",
  unicode: "你好，DevKit",
  timestamp: String(Math.floor(Date.now() / 1000)),
  datecalc: "2026-07-15\n2026-07-22 00:12:31",
  timeunits: "90 min\n1.5 h\n2 days",
  iso8601: "2026-09-23T08:30:15+08:00\n2026-09-22T16:30:15Z",
  semver: "1.4.0-beta.2\n1.4.0",
  dateconvert: "20260715\n2026-07-15\n2026-07-15 00:00:00\n2026-07-22T00:12:31.000Z\n2026-07-22T00:12:31",
  filesize: "1.5 GB\n700 MiB\n4096",
  radix: "255",
  chinese: "开发者工具箱，让编码转换更简单。",
  case: "Hello DevKit 你好",
  ascii: "DevKit 你好",
  escape: '第一行\n第二行："DevKit"',
  rmb: "123456.78",
  pinyin: "开发者工具箱",
  hash: "Hello DevKit",
  uuid: "5",
  password: "16",
  text: "Hello DevKit\n这是一段测试文本。",
  regex: "/dev(kit)?/gi\nDevKit makes dev work easier.",
  jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGV2S2l0IiwiaWF0IjoxNTE2MjM5MDIyfQ.signature",
  json2ts: '{"name":"DevKit","version":2,"ready":true}',
  query: "https://example.com/search?q=devkit&page=2",
  color: "#41e0c2",
  markdown: "# DevKit\n\n**私密、高效**的 `开发者工具箱`\n\n- 本地处理\n- 即开即用",
  diff: "原来的第一行\n相同内容\n--- 对比 ---\n修改后的第一行\n相同内容",
  naming: "hello developer toolbox",
  entities: '<button title="DevKit">开始</button>',
  cron: "*/15 9-18 * * 1-5",
  curl: "curl -X POST https://api.example.com/users -H 'Content-Type: application/json' -d '{\"name\":\"DevKit\"}'",
  cidr: "192.168.1.10/24",
  units: "24",
  contrast: "#41e0c2\n#091011",
  sql: "select id,name from users where active=1 order by created_at desc",
  yaml: '{"name":"DevKit","version":3,"features":["local","fast"]}',
  dedupe: "苹果\n香蕉\n苹果\n橙子\n香蕉",
  sortlines: "项目10\n项目2\n苹果\n香蕉\n项目1",
  "md5-32-lower": "Hello DevKit",
  "md5-32-upper": "Hello DevKit",
  "md5-16-lower": "Hello DevKit",
  "md5-16-upper": "Hello DevKit",
  sha1: "Hello DevKit",
  "sha2-256": "Hello DevKit",
  "sha2-512": "Hello DevKit",
  "sha3-512": "Hello DevKit",
  "sha3-384": "Hello DevKit",
  "sha3-256": "Hello DevKit",
  "sha3-224": "Hello DevKit",
  "ripemd-160": "Hello DevKit",
  "crc32-64": "Hello DevKit",
  "aes-encrypt": '{"text":"Hello DevKit","key":"change-this-passphrase"}',
  "des-encrypt": '{"text":"Hello DevKit","key":"change-this-passphrase"}',
  "tripledes-encrypt": '{"text":"Hello DevKit","key":"change-this-passphrase"}',
  "rabbit-encrypt": '{"text":"Hello DevKit","key":"change-this-passphrase"}',
  "rc4-encrypt": '{"text":"Hello DevKit","key":"change-this-passphrase"}',
  "aes-decrypt": '{"text":"U2FsdGVkX1842Gxb/cC9y5aoZxLXJWM0YIS22It7DRY=","key":"change-this-passphrase"}',
  "des-decrypt": '{"text":"U2FsdGVkX18TPhf8jvUJlDSpoxy42Olmf2gFUKVj5kg=","key":"change-this-passphrase"}',
  "tripledes-decrypt": '{"text":"U2FsdGVkX19h8bx1KnMyE1fL8TAcMKNsYy8FFFFbf6A=","key":"change-this-passphrase"}',
  "rabbit-decrypt": '{"text":"U2FsdGVkX18+dmRrph8jGsNupOHr3j47yuBqtA==","key":"change-this-passphrase"}',
  "rc4-decrypt": '{"text":"U2FsdGVkX19X9ByWcRJ8oM6iySXKjmnpja/keQ==","key":"change-this-passphrase"}',
  ...p0Samples,
};
